[package]
name = "cli-alarm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
rodio = "0.15"
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
