[package]
name = "cli-alarm"
version = "0.3.0"
edition = "2021"
description = "A simple CLI alarm saying a message after a certain amount of time."
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }

[[bin]]
name = "alarm"
path = "src/main.rs"
